name: Python Mini Projects CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Only installs if you've created a requirements file
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        pip install flake8
        # This step stops the build if there are critical Python syntax errors
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # This step reports warnings but doesn't stop the build
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
